### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by pcg92** [jiteshmohite/Android-Network-Connectivity#2]
I need to detect when the user changes the ip/network, is it possible with this code?

**Comment by isabsent** [comment]
Yes, would be nice to know it when app is in background.

**Comment by isabsent** [comment]
Works for me on device with API 24 when app is in background and foreground.

**Comment by pcg92** [comment]
and what about android 8? 💃

**Comment by isabsent** [comment]
You can try if you have Android 8.

**Comment by CristianFanjulWiFiesta** [comment]
In my case is not working in the following scenario with Android Oreo:
Open the app, close it and wait one hour (or a few minutes might be enough). 
Connection changes are not detected.
Can someone else try? 
Is this working in nougat?

**Comment by dungnguyendotme** [comment]
I confirm that it's DOES NOT auto detect the connection when turn on/off wifi or Mobile Network (in Android 7)
Just only check by click in the button. 
If just only check by click. Damn. Waste too much time for this fucking shit project.
